
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tubu_development


test:
  <<: *default
  database: tubu_test

production:
  <<: *default
  database: tubu_production
  username: tubu
  password: <%= ENV['TUBU_DATABASE_PASSWORD'] %>
